# configuration
# fill in the course details
 
courseName: ITP 348 - Intro to Physical Computing

# small title that is at the top of every page
subtitle: Course Content

# baseurl is the same as the name of the repository
baseurl: /gh-syllabus

# url where the required reading is available to download
docsUrl: "" 

# url where the student's grading info is kept
gradingUrl: "https://blackboard.usc.edu" 

# change only if you know what you are doing
collections:
  syllabus:
    output: true
  testlect:
    output: true
defaults:
  - scope:
      path: ""
      type: syllabus
    values:
      layout: unit
  - scope:
      path: ""
      type: testlect
    values:
      layout: unit
# theme: jekyll-theme-dinky
